# Generated by Django 2.2.1 on 2019-05-14 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj_tasks', '0002_auto_20190513_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_header',
            field=models.CharField(max_length=200),
        ),
    ]
