# Generated by Django 2.2.1 on 2019-05-18 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj_tasks', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
