# Generated by Django 2.2.1 on 2019-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_tasks', '0006_task_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('To_Do', 'To-Do'), ('In_Progress', 'In-Progress'), ('Done', 'Done')], default='To_Do', max_length=15),
        ),
        migrations.DeleteModel(
            name='Task_Category',
        ),
    ]
