# Generated by Django 2.2.1 on 2019-05-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_tasks', '0008_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proj_tasks.Project'),
            preserve_default=False,
        ),
    ]
